import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Navbar from "../components/Navbar";
import LoadingScreen from "../components/LoadingScreen";
import PortfolioLabel from "../components/PortfolioLabel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-green-400 font-mono`}
      >
        <LoadingScreen />
        <PortfolioLabel />
        <Navbar />
        <main className="min-h-screen w-full flex flex-col items-center justify-start pt-8">
          {children}
        </main>
      </body>
    </html>
  );
}
